### PR TITLE
chore: update README.md to include additional instructions

### PR DESCRIPTION
**Pull request by DoctorDerek**
✅ chore: update README.md to include additional instructions

🟩 I'll open a follow-up PR to update the package dependencies and include a `.nvmrc` file.

### CODE REVIEW

**Comment by DoctorDerek** [comment]
I'm not quite sure how to preview the Markdown changes without merging them on the GitHub website, but you can preview them in VSCode using the Cmd+Shift+V shortcut. @lifeofzero @jonatassales

**Comment by jonatassales** [comment]
@DoctorDerek To enable preview we can create an integration in Vercel with this repo. What do you think?

**Review by jonatassales — APPROVED** [review]
Awesome. Thanks @DoctorDerek!

**Comment by DoctorDerek** [comment]
> @DoctorDerek To enable preview we can create an integration in Vercel with this repo. What do you think?

@jonatassales Makes sense to me. I'll add it to my list to look into.

**Pull request merged**
