### PR TITLE
Chore/update nextjs version

### PR DESCRIPTION
**Pull request by DoctorDerek**
✅ chore: add prettier
 

✅ chore: run prettier
 

✅ chore: add ESLint and update all dependencies with yarn remove && yarn add
 

✅ chore: create .nvmrc file
 

✅ chore: install lint-staged and husky pre-commit script to run prettier and eslint
 

✅ chore: move sample.env to .env.sample and add code comment
 

✅ chore: add prettier to run on .css files
 

✅ chore: add additional comments to .env.sample
 

✅ fix: downgrade "@date-io/date-fns": "^1.3.13" to fix RangeError
https://stackoverflow.com/questions/59600125/cannot-get-material-ui-datepicker-to-work
 

✅ fix: use relative: LAST_YEAR in default CounterQuery instead of PREVIOUS_WEEK
 

✅ fix: flex bug hiding chart and refactor to Tailwind styles while fixing bug
 

✅ chore: add gitlog package.json command
 

✅ chore: add message body (in addition to subject) to gitlog
https://git-scm.com/docs/git-log
 

✅ chore: run ESLint after Prettier to remove space before function parentheses via VS Code workspace settings
```
/**
 * Note: This repo requires ESLint to be run after Prettier.
 * (The reason we need to run ESLint 2nd is the space-before-func-parens rule.)
 * To do so in VS Code, you need to use an extra extension.
 *
 * Reference: https://github.com/rohit-gohri/vscode-format-code-action
 *
 * Step 1: Make sure you've installed the VS Code Prettier & ESLint extensions:
 *    https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
 *    https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
 * Step 2: On the command line, install the extra extension:
 *         code --install-extension rohit-gohri.format-code-action
 * Step 3: Use either File -> Open Workspace from File... or the command line:
 *         code sample-app-nextjs.code-workspace
 * Step 4: You should now be set up correctly using the local workspace file.
 */
```
 

✅ chore: run ESLint after Prettier on repo to remove space before function parentheses
 

✅ chore: use .gitignore as .prettierignore file for yarn format command
 

✅ chore: add singleQuote: true and trailingComma: "none" to .pretierrc.js
 

✅ chore: run yarn format and yarn lint
 

✅ chore: add yarn formatlint command

### CODE REVIEW

**Comment by DoctorDerek** [comment]
Sorry for the noisy PR. Prettier touched basically every file, but the good news is I set up a precommit git hook to run Prettier and ESLint, and I upgraded all the dependencies I could. @Felipe-Cadavid @jonatassales

**Comment by DoctorDerek** [comment]
Got it, thanks @jonatassales! I appreciate the detailed feedback. I had been wondering why I didn't see a Prettier configuration file anywhere (and why the HOWEs mention using VSCode's built-in formatter). 

I updated the PR per your recommendations.

**Review by jonatassales — APPROVED** [review]
If you want to remove that `"space-before-function-paren": ["warn", "always"]` I think it'll make the repo less complicated so you don't need to do that workaround with vscode.

**Comment by jonatassales** [comment]
Closing since @DoctorDerek did some changes in another [PR](https://github.com/propeldata/sample-app-nextjs/pull/7) which replaces this one.

**Pull request closed without merging**
